# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14706e62ebafc96631ad05a279ee52e040dda3809ea31fa2d57dbf27e5bd8fd411071199bd8c3d9f71b925bcd677add303dc84a9e1310e5d94a9c16630712265

test:
  secret_key_base: dd6fdb0e137ac39fb7292c7c550ae209e0a73371168856c0043b6df0c83a636d08832d2690c95f5be0435fd295d4834d4711f506dc406b7edaacecc397c45b2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
